# Generated by Django 3.1.6 on 2021-02-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTelefona')),
                ('markaTelefona', models.TextField()),
                ('modelTelefona', models.TextField()),
                ('slikaTelefona', models.TextField()),
                ('opisModela', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idKomentara')),
                ('sadrzaj', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telefon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porukeApp.telefoni')),
            ],
        ),
    ]
