# Generated by Django 3.1.4 on 2021-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porukeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefoni',
            name='idTelefona',
        ),
        migrations.AddField(
            model_name='telefoni',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Komentar',
        ),
    ]
